const navLinks = [
  {
    id: 1,
    name: "Projects",
    type: "finder",
  },
  {
    id: 3,
    name: "Contact",
    type: "contact",
  },
  {
    id: 4,
    name: "Resume",
    type: "resume",
  },
];

const navIcons = [
  {
    id: 1,
    img: "/icons/wifi.svg",
  },
  {
    id: 2,
    img: "/icons/search.svg",
  },
  {
    id: 3,
    img: "/icons/user.svg",
  },
  {
    id: 4,
    img: "/icons/mode.svg",
  },
];

const dockApps = [
  {
    id: "finder",
    name: "Portfolio", // was "Finder"
    icon: "finder.png",
    canOpen: true,
  },
  {
    id: "safari",
    name: "Articles", // was "Safari"
    icon: "safari.png",
    canOpen: true,
  },
  {
    id: "photos",
    name: "Gallery", // was "Photos"
    icon: "photos.png",
    canOpen: true,
  },
  {
    id: "contact",
    name: "Contact", // or "Get in touch"
    icon: "contact.png",
    canOpen: true,
  },
  {
    id: "terminal",
    name: "Skills", // was "Terminal"
    icon: "terminal.png",
    canOpen: true,
  },
  {
    id: "trash",
    name: "Archive", // was "Trash"
    icon: "trash.png",
    canOpen: false,
  },
];

// Each post: { id, date, title, image, link?, content? }
// Posts with `content` open in the in-app text reader; posts with `link` open externally.
const blogPosts = [
  {
    id: 1,
    date: "May 30, 2026",
    title: "Real-Time Pitch Shifting in the Browser: How TransposeMe Works",
    image: "/images/projects/transposeme.webp",
    content: [
      "TransposeMe lets you paste a YouTube link or drop in an audio file, drag a slider, and hear the song in a different key instantly, with the tempo untouched. Here's what it actually takes to make that work in a browser.",
      "",
      "Why the obvious approach fails:",
      "Every <audio> element has a playbackRate property, and changing it does shift pitch but it also changes speed, because pitch and tempo are coupled in the time domain. Slow a song down 20% and it drops a couple of semitones into sludge. Decoupling them requires a time-stretching algorithm: the audio has to be re-synthesised, not just replayed faster or slower.",
      "",
      "The engine:",
      "TransposeMe runs Rubber Band, the professional phase-vocoder library used in real audio workstations, compiled to WebAssembly. Source audio is decoded to a raw AudioBuffer, pushed through rubberband-wasm with formant preservation, and scheduled back out through the Web Audio API, the WASM module is compiled once and reused across every call. For video files, ffmpeg.wasm copies the original video stream untouched and swaps in only the shifted audio track, so the result is still a watchable music video. All of this happens locally: your audio never leaves the machine.",
      "",
      "The hard parts:",
      "• Chunked processing. You can't stretch a large file in one synchronous call without freezing the tab. The pipeline processes audio in windows, keeps a lookahead buffer, and feeds the audio graph just ahead of the playhead.",
      "• Seamless key changes mid-song. When you drag the slider during playback, the engine has to restart processing from the current position with new parameters without an audible gap. Getting the position handoff sample-accurate took more iteration than any other feature.",
      "• YouTube ingestion. A Node.js/Express service uses yt-dlp (with an EJS challenge solver and parallel fragment download) to extract audio server-side, because browsers can't read YouTube streams directly. The shifted audio is rendered with the Rubber Band CLI, and the source is cached so every key you try afterward reuses that work.",
      "• Automatic key detection. A Python service running Essentia's KeyExtractor analyses the audio and returns the root and mode, so 'take it up to D' is one click instead of guesswork.",
      "",
      "What I learned:",
      "WebAssembly has quietly made the browser a legitimate DSP platform. The gap between 'web app' and 'desktop audio tool' is now mostly engineering discipline, buffer management, worker threads, and respecting the main thread rather than missing capability. TransposeMe also ships as an Electron app, and the core audio code is identical in both.",
    ],
  },
  {
    id: 2,
    date: "Apr 22, 2026",
    title: "Migrating a National Radio Station's CMS: Strapi v3 to v5, Live",
    image: "/images/projects/bfm.webp",
    content: [
      "BFM 89.9 publishes around the clock, live radio, podcasts, articles. Its content backbone was Strapi v3, two major versions behind, EOL, and blocking every other infrastructure upgrade. I owned the migration to v5. The constraint that shaped everything: the newsroom never stops, so the CMS could not either.",
      "",
      "Why it was hard:",
      "Strapi v3 to v5 is not an upgrade, it's a rewrite of your data's home. The database schema changed fundamentally (v5 introduces a document-based model), the REST response shape changed twice across v4 and v5, plugins and customisations had no direct equivalents, and years of editorial content, tens of thousands of entries with media, relations and embedded HTML, had to arrive intact.",
      "",
      "The approach:",
      "• Run both stacks in parallel. The v5 instance was stood up alongside production v3 on AWS, with migration scripts that could be re-run idempotently. Content synced repeatedly during the transition window, so cutover day moved a delta, not a database.",
      "• Migrate by content type, verify by sampling. Each content type got a transform script and an automated count-and-checksum comparison, plus manual spot checks on the entries editors actually cared about.",
      "• Build an API compatibility layer. The front end consumed v3-shaped responses; rewriting every consumer at the same time as the backend would have doubled the risk. A thin adapter normalised v5 responses so the site could switch backends before switching response handling.",
      "• Cut over behind the CDN. With CloudFront in front, the origin switch was invisible to listeners; cached pages held while the new origin warmed up.",
      "",
      "The result:",
      "Editors logged into the new CMS on a Monday morning and kept publishing. No missed shows, no broken article URLs, no SEO cliff. The unglamorous parts, idempotent scripts, checksum verification, the compatibility layer, were exactly the parts that made it boring, which is the highest compliment a migration can get.",
    ],
  },
  {
    id: 3,
    date: "Mar 18, 2026",
    title: "Offline-First by Design: Building ChordVault as a PWA",
    image: "/images/projects/chordvault.webp",
    content: [
      "ChordVault is a chord sheet manager for musicians. Its defining requirement came from the stage, not the spec sheet: when you're mid-set and the venue Wi-Fi dies, your songs must still open. That single constraint drove the whole architecture.",
      "",
      "The architecture:",
      "Supabase (Postgres + Auth, with row-level security) is the single source of truth. Authoritative data, songs and setlists, lives in Postgres and syncs across every device. Ephemeral per-device state, transpose offset, capo, BPM, fonts, themes and voicing favorites, lives in localStorage for instant, offline-safe reads. Keeping those two concerns apart is what makes the whole thing predictable.",
      "",
      "The service worker layer:",
      "vite-plugin-pwa with Workbox precaches the app shell, so the app itself opens with no connection at all, and wraps the Supabase calls in a NetworkFirst strategy (5-second timeout, up to 200 entries, 30-day retention). Wi-Fi dies at the venue and the songs you've already opened stay fully readable. The split matters: Workbox owns the code and the cached network data, localStorage owns your preferences, so an app update can't wipe your settings and clearing preferences can't break the app.",
      "",
      "Transposition without tears:",
      "Chord transposition looks like string replacement and absolutely is not. Move 'F#m7' up four semitones and the right answer depends on the destination key's spelling, A#m7 in some contexts, Bbm7 in others. ChordVault delegates all of it to tonal, a proper music theory engine, so enharmonics stay correct in every key. The lesson generalises: when a domain has real theory, use a library built on the theory instead of regexing your way to 80% correct.",
      "",
      "Other details that earned their keep:",
      "• Songbook import via mammoth (DOCX) and pdf.js (PDF, with positional line reconstruction so chord alignment survives), because musicians' sheets already live in those files, meeting users where their data is mattered more than any feature.",
      "• PDF export via html2canvas + jsPDF, rendering exactly what's on screen so printed setlists match the app.",
      "• Drag-and-drop setlist ordering with @dnd-kit, with order, plus a per-setlist key and capo override, persisted per slot.",
      "",
      "The whole product runs on free tiers, Supabase, Vercel, end to end. Offline-first turned out to be the cheapest reliability strategy available: the best way to survive a flaky network is to stop needing it.",
    ],
  },
];

const techStack = [
  {
    category: "Frontend",
    items: [
      "React.js",
      "Next.js",
      "TypeScript",
      "Context API",
      "Custom Hooks",
      "Data Caching",
      "Performance Optimization",
    ],
  },
  {
    category: "Testing & Security",
    items: ["Jest", "React Testing Library", "Secure API Consumption"],
  },
  {
    category: "Cloud & Infrastructure",
    items: ["AWS (EC2, S3, CloudFront, CloudSearch)", "Vercel", "CI/CD"],
  },
  {
    category: "Media & Native APIs",
    items: [
      "Live Stream/Podcast Integration",
      "Native Web APIs",
      "Ad-Tech",
      "Cross-Browser Compatibility",
    ],
  },
  {
    category: "State & Data",
    items: [
      "RESTful API Integration",
      "Strapi (Legacy Migration)",
      "Firebase",
      "Webhooks",
    ],
  },
  {
    category: "Design & UI",
    items: [
      "Tailwind CSS",
      "SCSS",
      "Responsive Component Architecture",
      "Figma",
    ],
  },
  {
    category: "Dev Tools",
    items: ["Git", "GitHub", "GitLab", "Vercel", "Docker"],
  },
];

const socials = [
  {
    id: 1,
    text: "Github",
    icon: "/icons/github.svg",
    bg: "#f4656b",
    link: "https://github.com/ShernNing",
  },
  {
    id: 4,
    text: "LinkedIn",
    icon: "/icons/linkedin.svg",
    bg: "#05b6f6",
    link: "https://www.linkedin.com/in/shern-ning-tan-942527106/",
  },
];

const photosLinks = [
  {
    id: 1,
    icon: "/icons/gicon1.svg",
    title: "Library",
  },
  {
    id: 2,
    icon: "/icons/gicon2.svg",
    title: "Memories",
  },
  {
    id: 3,
    icon: "/icons/file.svg",
    title: "Places",
  },
  {
    id: 4,
    icon: "/icons/gicon4.svg",
    title: "People",
  },
  {
    id: 5,
    icon: "/icons/gicon5.svg",
    title: "Favorites",
  },
];

const gallery = [
  {
    id: 1,
    img: "/images/gal1.jpg",
  },
  {
    id: 2,
    img: "/images/gal2.jpg",
  },
  {
    id: 3,
    img: "/images/gal3.jpg",
  },
  {
    id: 4,
    img: "/images/gal4.jpg",
  },
];

export {
  navLinks,
  navIcons,
  dockApps,
  blogPosts,
  techStack,
  socials,
  photosLinks,
  gallery,
};

const WORK_LOCATION = {
  id: 1,
  type: "work",
  name: "Work",
  icon: "/icons/work.svg",
  kind: "folder",
  children: [
    {
      id: "bfm",
      name: "BFM 89.9",
      icon: "/images/folder.png",
      kind: "folder",
      position: "top-8 left-4",
      windowPosition: "top-[12vh] right-[2.5vw]",
      children: [
        {
          id: 1,
          name: "About.txt",
          icon: "/images/txt.png",
          kind: "file",
          fileType: "txt",
          position: "top-8 left-8",
          subtitle:
            "BFM 89.9, Malaysia's Business Radio Station (Professional Work)",
          description: [
            "The official website of BFM 89.9, Malaysia's only independent business radio station, a 24/7 digital hub for business, economics and current-affairs content: live radio, an on-demand archive of thousands of podcasts, plus articles, videos and events across Business, Personal Finance, Current Affairs, Arts & Culture and Health. Installable as a PWA.",
            "",
            "My Role:",
            "Front-End Developer owning the public web platform end to end, feature development, performance, infrastructure and CMS migrations for a high-traffic national media site that runs with no dedicated manager layer.",
            "",
            "Built with:",
            "Next.js 14 (App Router, SSR/ISR) + React 18 + TypeScript, Material-UI 5 + Emotion, Zustand (global audio player), TanStack Query, Firebase (Auth + Realtime Database for bookmarks and history), Omny.fm (podcasts) and Triton Digital (live stream), AWS (S3, CloudSearch), OneSignal push, Revive Adserver, GA4, Resend, next-pwa.",
            "",
            "What it does:",
            "• A global, persistent audio player (Omny podcasts + Triton live stream) that survives page navigation without dropping audio",
            "• Personal accounts: sign in with email, Google, Facebook or Apple, with bookmarks, listen/read history and 'continue listening' resume",
            "• Full-text search across podcasts, articles, videos and events via AWS CloudSearch",
            "• Show, category and tag pages, events with email registration, and web push notifications",
            "",
            "Challenges overcome:",
            "• Keeping live-stream and podcast audio playing seamlessly across client-side route changes",
            "• Large-scale Strapi CMS migration (v3 to v5) with zero editorial downtime",
            "• High-traffic performance: SSR/ISR, caching, CloudFront CDN strategy and efficient re-render cycles",
            "• Ad-tech integration (Revive) and cross-browser audio playback quirks",
          ],
        },
        {
          id: 2,
          name: "Live Site",
          icon: "/images/safari.png",
          kind: "file",
          fileType: "url",
          href: "https://www.bfm.my/",
          position: "top-28 left-52",
        },
        {
          id: 3,
          name: "Preview.png",
          icon: "/images/image.png",
          kind: "file",
          fileType: "img",
          imageUrl: "/images/projects/bfm.webp",
          position: "top-52 right-8",
        },
        {
          id: 4,
          name: "Demo.mp4",
          icon: "/images/image.png",
          kind: "file",
          fileType: "video",
          videoUrl: "/videos/bfm.mp4",
          position: "top-52 left-8",
        },
      ],
    },
    {
      id: "managerpro",
      name: "ManagerPro",
      icon: "/images/folder.png",
      kind: "folder",
      position: "top-8 left-52",
      windowPosition: "top-[30vh] right-[2.5vw]",
      children: [
        {
          id: 1,
          name: "About.txt",
          icon: "/images/txt.png",
          kind: "file",
          fileType: "txt",
          position: "top-10 left-32",
          subtitle:
            "BFM ManagerPro, Radio Station Management System (Professional Work)",
          description: [
            "The internal content management system that powers BFM's publishing, the production dashboard where editorial, podcast and video teams create, edit, schedule and publish podcasts, videos, articles and events, which are then served to BFM's public site and apps. (Internal tool, the live link shows the login gate.)",
            "",
            "The Problem:",
            "A radio station's editorial workflow, recording and uploading episodes, transcribing them, writing show notes, cropping images, scheduling content, needs one purpose-built, role-aware tool instead of a patchwork of generic CMS screens and raw Strapi admin access.",
            "",
            "Built with (v3 rebuild):",
            "Next.js 16 (App Router) + React 19 + TypeScript (strict), Tailwind CSS v4, Radix UI primitives, TanStack Query v5, Zustand, react-hook-form + Zod, TipTap v3 rich-text editor, Strapi 5 backend, AWS S3 (direct browser-to-S3 multipart upload), hosted on Vercel. (The original v2 ran on Nuxt 2 / Vue 2; v3 is a full rewrite, currently in progress.)",
            "",
            "What it does:",
            "• Unified, role-aware dashboard (admin / video producer / editor) for podcasts, videos, articles, events and the 'Allegedly Viral' feed",
            "• Podcast pipeline tracking across Omny (hosting), Redtone (transcription) and n8n (orchestration), with edit-locking and auto-polling while jobs run",
            "• Transcripts with speaker diarization, AI-assisted summaries and suggested titles",
            "• Rich-text articles, scheduled publishing, image cropping and drag-to-reorder queues",
            "",
            "Challenges overcome:",
            "• JWT security: the Strapi token never reaches the browser, all API traffic flows through a server-side proxy that injects it from an httpOnly cookie",
            "• Large uploads on Vercel: media (video up to 10 GB, audio, images) uploads browser-to-S3 via presigned multipart URLs, bypassing Vercel's ~4.5 MB body cap",
            "• Tracking multi-service podcast jobs and safely editing metadata without clobbering an in-flight pipeline",
            "• Role-based access control reflected throughout the navigation, with per-user podcast-show scoping",
          ],
        },
        {
          id: 2,
          name: "Live Site",
          icon: "/images/safari.png",
          kind: "file",
          fileType: "url",
          href: "https://managerpro-v2.vercel.app/",
          position: "top-6 right-10",
        },
        {
          id: 3,
          name: "Preview.png",
          icon: "/images/image.png",
          kind: "file",
          fileType: "img",
          imageUrl: "/images/projects/managerpro.webp",
          position: "top-36 left-6",
        },
        {
          id: 4,
          name: "Source Code",
          icon: "/icons/github-dark.svg",
          kind: "file",
          fileType: "url",
          href: "https://github.com/ShernNing/managerpro-v3",
          position: "top-32 left-72",
        },
        {
          id: 5,
          name: "Demo.mp4",
          icon: "/images/image.png",
          kind: "file",
          fileType: "video",
          videoUrl: "/videos/managerpro.mp4",
          position: "top-56 left-40",
        },
      ],
    },
    {
      id: "chordvault",
      name: "ChordVault",
      icon: "/images/folder.png",
      kind: "folder",
      position: "top-8 right-4",
      windowPosition: "top-[12vh] right-[11vw]",
      children: [
        {
          id: 1,
          name: "About.txt",
          icon: "/images/txt.png",
          kind: "file",
          fileType: "txt",
          position: "top-6 left-6",
          subtitle: "ChordVault, Personal Chord Sheet Manager for Musicians",
          description: [
            "A searchable, transposable library for every song you play, cloud-synced across devices, performance-ready, and fully readable offline on stage.",
            "",
            "The Problem:",
            "Musicians hoard chord sheets across paper binders, Word docs, screenshots and notes apps. Finding the right version of a song mid-rehearsal, in the right key, is slow, and none of it works reliably offline when the venue Wi-Fi dies.",
            "",
            "What it does:",
            "• Library with real-time search, tags, key filter and play-count sorting; paste a sheet and the parser auto-detects the format, cleans bar notation and normalises Unicode sharps/flats",
            "• Automatic key detection and artist auto-lookup (MusicBrainz), with uncertain lines flagged instead of silently misparsed",
            "• One-tap, music-theory-correct transposition (enharmonics, slash chords, extensions), capo intelligence and a Nashville Number System toggle",
            "• Stage Mode (black background, high-contrast chords), hands-free auto-scroll, and a sample-accurate Web Audio metronome with tap tempo",
            "• Setlist builder with drag-and-drop and per-setlist key/capo overrides; bulk-import a whole songbook from DOCX/PDF with a review-and-dedupe screen",
            "• Export band-ready handouts to PDF/DOCX, plus a built-in guitar voicing study suite (triads, sevenths, progressions, capo helper, practice drills)",
            "• Installable PWA, previously viewed songs stay readable with no connection",
            "",
            "Built with:",
            "React 18 + Vite, Tailwind CSS, Supabase (Postgres + Auth + row-level security), tonal (music-theory engine) with custom enharmonic / key-detection / Nashville logic, Tone.js + Web Audio, @dnd-kit, jsPDF + html2canvas, docx + mammoth + pdf.js, vite-plugin-pwa + Workbox. Hosted on Vercel, runs on free tiers end to end.",
            "",
            "Challenges overcome:",
            "• Transposition is music theory, not string replacement, used the tonal engine to keep enharmonics correct (F# vs Gb) across every key, covered by unit tests",
            "• Splitting and parsing messy real-world DOCX/PDF songbooks into clean, structured songs, with PDF Y-coordinate line reconstruction so chord alignment survives",
            "• Offline-first architecture: Supabase as source of truth with a Workbox NetworkFirst cache (5s timeout, 200 entries, 30-day retention), so a gig never depends on venue Wi-Fi",
            "• A sample-accurate metronome built on lookahead Web Audio scheduling instead of jittery setInterval",
          ],
        },
        {
          id: 2,
          name: "Live Site",
          icon: "/images/safari.png",
          kind: "file",
          fileType: "url",
          href: "https://chordvault-ten.vercel.app/",
          position: "top-6 right-6",
        },
        {
          id: 3,
          name: "Preview.png",
          icon: "/images/image.png",
          kind: "file",
          fileType: "img",
          imageUrl: "/images/projects/chordvault.webp",
          position: "top-28 left-44",
        },
        {
          id: 4,
          name: "Source Code",
          icon: "/icons/github-dark.svg",
          kind: "file",
          fileType: "url",
          href: "https://github.com/ShernNing/chordvault",
          position: "top-56 left-6",
        },
        {
          id: 5,
          name: "Demo.mp4",
          icon: "/images/image.png",
          kind: "file",
          fileType: "video",
          videoUrl: "/videos/chordvault.mp4",
          position: "top-56 right-6",
        },
      ],
    },
    {
      id: "transposeme",
      name: "TransposeMe",
      icon: "/images/folder.png",
      kind: "folder",
      position: "top-48 left-4",
      windowPosition: "top-[30vh] right-[11vw]",
      children: [
        {
          id: 1,
          name: "About.txt",
          icon: "/images/txt.png",
          kind: "file",
          fileType: "txt",
          position: "top-60 left-56",
          subtitle: "TransposeMe, Shift Pitch & Tempo of Any Audio, Instantly",
          description: [
            "Shift the pitch and tempo of any YouTube video or audio/video file, processed locally in your browser, instantly, with no uploads.",
            "",
            "The Problem:",
            "Singers and musicians constantly need a song in a different key (or at a slower tempo) to perform or practise. The usual options are a heavyweight DAW round-trip, or online tools that upload your audio to someone else's server.",
            "",
            "What it does:",
            "• Paste a YouTube link or drop in a file, MP3, WAV, FLAC, AAC, M4A, MP4, MOV, WebM, up to 5 GB",
            "• Drag a slider or pick a target key; pitch shifts in real time with tempo preserved, or flip to Tempo mode (0.5x–2x) with pitch preserved",
            "• Playback resumes from the exact same timestamp when you change keys mid-song; A/B toggle between original and transposed",
            "• Automatic key detection, a live 12-key grid and a diatonic chord chart that updates as you transpose",
            "• Auto-fetches a chord sheet (ChordVault first, then the web), transposes it to your new key, and exports MP3/MP4 audio or PDF/DOCX charts",
            "• Also packaged as an Electron desktop app",
            "",
            "Built with:",
            "React 19 + Vite, Tailwind CSS, Web Audio API. In-browser DSP via rubberband-wasm (WebAssembly Rubber Band) with ffmpeg.wasm remuxing video; a Node.js/Express backend uses yt-dlp for YouTube extraction and the Rubber Band CLI for server-side renders; a Python + Essentia service handles key detection. PWA + Electron.",
            "",
            "Challenges overcome:",
            "• Real-time, tempo-preserving pitch shifting in the browser using WASM DSP without audible glitches",
            "• Keeping playback position sample-accurate while the user sweeps through keys mid-playback",
            "• Handling multi-gigabyte media files in a web app, and remuxing video so the transposed file stays watchable",
            "• Orchestrating a pipeline that spans browser WASM, a Node backend (with caching, rate limiting and Helmet) and a Python key-detection service",
          ],
        },
        {
          id: 2,
          name: "Live Site",
          icon: "/images/safari.png",
          kind: "file",
          fileType: "url",
          href: "https://transposeme.vercel.app/",
          position: "top-10 left-4",
        },
        {
          id: 3,
          name: "Preview.png",
          icon: "/images/image.png",
          kind: "file",
          fileType: "img",
          imageUrl: "/images/projects/transposeme.webp",
          position: "top-40 left-36",
        },
        {
          id: 4,
          name: "Source Code",
          icon: "/icons/github-dark.svg",
          kind: "file",
          fileType: "url",
          href: "https://github.com/ShernNing/transposeme",
          position: "top-10 left-72",
        },
        {
          id: 5,
          name: "Demo.mp4",
          icon: "/images/image.png",
          kind: "file",
          fileType: "video",
          videoUrl: "/videos/transposeme.mp4",
          position: "top-40 right-4",
        },
      ],
    },
    {
      id: "workout-tracker",
      name: "Workout Tracker",
      icon: "/images/folder.png",
      kind: "folder",
      position: "top-48 left-52",
      windowPosition: "top-[48vh] right-[11vw]",
      children: [
        {
          id: 1,
          name: "About.txt",
          icon: "/images/txt.png",
          kind: "file",
          fileType: "txt",
          position: "top-6 right-8",
          subtitle: "Workout Tracker, Your Personal Strength Journal",
          description: [
            "A full progressive-overload training app, plan, log, analyse, adjust, that works like a personal lifting coach. Installable PWA, fully usable offline at the gym.",
            "",
            "The Problem:",
            "Progressive overload means lifting a little more than last time, consistently, for years, which requires being a database and a coach at once. Notes apps can't compute progression, paper can't chart it, and logging between sets has to be near-instant or it doesn't happen.",
            "",
            "What it does:",
            "• One-handed set logging (weight, reps, RPE), kg/lbs toggle, a rest timer with screen wake-lock, and a plate calculator",
            "• A coaching engine that reads your history and RPE to suggest the next load (weight up / hold / deload), modified by a daily readiness score and muscle-recovery status",
            "• Automatic PR detection with confetti, a recommended next workout, and a 7-day split plus a 100+ exercise library with mid-session swaps",
            "• Progress analytics: volume and frequency trends, estimated 1RMs, strength-standard tiers, calendar heatmap and dynamically computed achievements",
            "• Mesocycle periodization, custom plans, cardio/goals/nutrition logging, Evolt 360 body-composition PDF import, and CSV/JSON export",
            "",
            "Built with:",
            "React 18 + Vite, Tailwind CSS, React Router v6, Supabase (Postgres + Auth + row-level security), Recharts, Framer Motion, @dnd-kit, vite-plugin-pwa + Workbox. Hosted on Vercel.",
            "",
            "Challenges overcome:",
            "• Designing a logging flow fast enough to use between sets, minimal taps, large touch targets, defaults seeded from the previous session",
            "• Building the coach/progression engine (RPE-based with a rep-range fallback) and a recovery model on top of raw set logs",
            "• An offline write queue: sessions are created locally, then upserted to Supabase on reconnect, so the app never blocks on signal",
            "• Lazy session creation and resume/merge logic so partial and duplicate same-day sessions reconcile cleanly",
          ],
        },
        {
          id: 2,
          name: "Live Site",
          icon: "/images/safari.png",
          kind: "file",
          fileType: "url",
          href: "https://workouttracker-xi.vercel.app/",
          position: "top-24 left-64",
        },
        {
          id: 3,
          name: "Preview.png",
          icon: "/images/image.png",
          kind: "file",
          fileType: "img",
          imageUrl: "/images/projects/workout-tracker.webp",
          position: "top-40 left-28",
        },
        {
          id: 4,
          name: "Source Code",
          icon: "/icons/github-dark.svg",
          kind: "file",
          fileType: "url",
          href: "https://github.com/ShernNing/workouttracker",
          position: "top-56 left-4",
        },
        {
          id: 5,
          name: "Demo.mp4",
          icon: "/images/image.png",
          kind: "file",
          fileType: "video",
          videoUrl: "/videos/workout-tracker.mp4",
          position: "top-48 right-12",
        },
      ],
    },
    {
      id: "caijin",
      name: "Caijin 财今",
      icon: "/images/folder.png",
      kind: "folder",
      position: "top-48 right-4",
      windowPosition: "top-[48vh] right-[2.5vw]",
      children: [
        {
          id: 1,
          name: "About.txt",
          icon: "/images/txt.png",
          kind: "file",
          fileType: "txt",
          position: "top-52 left-44",
          subtitle:
            "Caijin 财今, Chinese-Language Business Media Platform (Professional Work)",
          description: [
            "BFM's Chinese-language financial media platform and the digital home for its Mandarin business content, podcasts and articles across 商业 Business, 股市 Markets, 创业 Entrepreneurship, 金融 Finance and 新闻 News, serving Malaysia's Chinese-speaking investors and professionals. Live at caijin.my.",
            "",
            "My Role:",
            "Front-End Developer leading the 2025 rebuild of the platform onto a modern, typed, server-rendered stack.",
            "",
            "Built with:",
            "Next.js 15 (App Router, Server Components) + TypeScript, Tailwind CSS v4, Radix UI with shadcn-style components, Zustand (podcast state), Embla Carousel, html-react-parser + isomorphic-dompurify, Biome. Content from the BFM CMS API, audio via Omny.fm, images on AWS S3.",
            "",
            "What it does:",
            "• Home with hero carousel, latest, trending and per-category highlight blocks",
            "• Category pages with Latest / Podcasts / Articles tabs; full article and podcast detail pages with an embedded Omny player and guest info",
            "• Global paginated search with keyword highlighting, and per-page SEO metadata (Open Graph / Twitter cards)",
            "",
            "Challenges overcome:",
            "• Rebuilding a legacy site onto Next.js + TypeScript while the publication kept running",
            "• Rendering CMS-authored HTML safely, sanitised through DOMPurify before parsing into React nodes",
            "• Server Components + force-dynamic for always-fresh content, with skeleton boundaries to prevent layout shift",
            "• Bilingual UI and typography tuned for Chinese-language content on a carousel-heavy, media-rich homepage",
          ],
        },
        {
          id: 2,
          name: "Live Site",
          icon: "/images/safari.png",
          kind: "file",
          fileType: "url",
          href: "https://www.caijin.my/",
          position: "top-12 left-24",
        },
        {
          id: 3,
          name: "Preview.png",
          icon: "/images/image.png",
          kind: "file",
          fileType: "img",
          imageUrl: "/images/projects/caijin.webp",
          position: "top-32 right-10",
        },
        {
          id: 4,
          name: "Demo.mp4",
          icon: "/images/image.png",
          kind: "file",
          fileType: "video",
          videoUrl: "/videos/caijin.mp4",
          position: "top-52 left-10",
        },
      ],
    },
  ],
};

const ABOUT_LOCATION = {
  id: 2,
  type: "about",
  name: "About me",
  icon: "/icons/info.svg",
  kind: "folder",
  children: [
    {
      id: 1,
      name: "me.png",
      icon: "/images/image.png",
      kind: "file",
      fileType: "img",
      position: "top-10 left-5",
      imageUrl: "/images/gal2.jpg",
    },
    {
      id: 2,
      name: "casual-me.png",
      icon: "/images/image.png",
      kind: "file",
      fileType: "img",
      position: "top-28 right-72",
      imageUrl: "/images/gal3.jpg",
    },
    {
      id: 3,
      name: "me-2.png",
      icon: "/images/image.png",
      kind: "file",
      fileType: "img",
      position: "top-52 left-80",
      imageUrl: "/images/gal4.jpg",
    },
    {
      id: 4,
      name: "about-me.txt",
      icon: "/images/txt.png",
      kind: "file",
      fileType: "txt",
      position: "top-60 left-5",
      subtitle: "Meet the Developer Behind the Code",
      image: "/images/gal2.jpg",
      description: [
        "Shern Ning Tan | Front-End Developer & Business Leader",
        "Date of Birth: 18/04/1993",
        "",
        "Professional Summary:",
        "An autonomous Front-End Developer with a background in Finance and Business Directorship. Expert in React and Next.js, specializing in high traffic media platforms and complex system migrations. Passionate about building resilient, testable React architecture that prioritizes data integrity and efficient re-rendering cycles. Proven ability to operate in ‘no manager’ environments, taking full ownership of project lifecycles, from large scale Strapi migrations (v3 to v5) to optimizing cloud infrastructure for global scalability.",
        "",

        "Technical Skills:",
        "• Expert React: Custom Hooks, Context API, Data Caching and Performance Optimization.",
        "• Testing & Security: Unit Testing (Jest, React Testing Library), focusing on edge case user interactions and secure API consumption.",
        "• Cloud & Infrastructure: AWS (EC2, S3, CloudFront, CloudSearch), Vercel and CI/CD.",
        "• Media & Native APIs: Global live stream/podcast player integration, native web APIs (Localstorage, Event listeners), ad-tech implementation and cross browser compatibility.",
        "• State & Data: RESTful API integration, Strapi (Legacy Migration), Firebase and Webhooks.",
        "• Design & UI: Tailwind CSS, SCSS, Responsive component architecture and Figma.",
        "",
        "Let's connect to discuss how I can bring value to your team!",
      ],
    },
  ],
};

const RESUME_LOCATION = {
  id: 3,
  type: "resume",
  name: "Resume",
  icon: "/icons/file.svg",
  kind: "folder",
  children: [
    {
      id: 1,
      name: "Resume.pdf",
      icon: "/images/pdf.png",
      kind: "file",
      fileType: "pdf",
      // you can add `href` if you want to open a hosted resume
      // href: "/your/resume/path.pdf",
    },
  ],
};

const TRASH_LOCATION = {
  id: 4,
  type: "trash",
  name: "Trash",
  icon: "/icons/trash.svg",
  kind: "folder",
  children: [
    {
      id: 1,
      name: "trash1.png",
      icon: "/images/image.png",
      kind: "file",
      fileType: "img",
      position: "top-10 left-10",
      imageUrl: "/images/trash-1.jpg",
    },
    {
      id: 2,
      name: "trash2.png",
      icon: "/images/image.png",
      kind: "file",
      fileType: "img",
      position: "top-40 left-80",
      imageUrl: "/images/trash-2.jpg",
    },
  ],
};

export const locations = {
  work: WORK_LOCATION,
  about: ABOUT_LOCATION,
  resume: RESUME_LOCATION,
  trash: TRASH_LOCATION,
};

const INITIAL_Z_INDEX = 1000;

const WINDOW_CONFIG = {
  finder: { isOpen: false, zIndex: INITIAL_Z_INDEX, data: null },
  contact: { isOpen: false, zIndex: INITIAL_Z_INDEX, data: null },
  resume: { isOpen: false, zIndex: INITIAL_Z_INDEX, data: null },
  safari: { isOpen: false, zIndex: INITIAL_Z_INDEX, data: null },
  photos: { isOpen: false, zIndex: INITIAL_Z_INDEX, data: null },
  terminal: { isOpen: false, zIndex: INITIAL_Z_INDEX, data: null },
  txtfile: { isOpen: false, zIndex: INITIAL_Z_INDEX, data: null },
  imgfile: { isOpen: false, zIndex: INITIAL_Z_INDEX, data: null },
  videofile: { isOpen: false, zIndex: INITIAL_Z_INDEX, data: null },
};

export { INITIAL_Z_INDEX, WINDOW_CONFIG };
